Create PR when push fails

diff --git a/.github/workflows/automerge.yml b/.github/workflows/automerge.yml
--- a/.github/workflows/automerge.yml
+++ b/.github/workflows/automerge.yml
@@ -54,19 +54,19 @@ jobs:
             echo "Merging source branch $source_branch into branch $release_branch"
             # Always create a merge commit (no fast forward)
             git merge --no-ff $source_branch
-            if [ $? -ne 0 ]
+            status=$?
+            if [ status -eq 0 ]
             then
-              echo "Merge failed. Opening pull request."
-              gh pr create --head $source_branch --base $release_branch --reviewer paychex-mbuzzelli --title "Automatic merge failure" --body "There was a merge conflict automatically merging this branch"
-              exit 0
-            else
               echo "Pushing commit"
               git push
-              if [ $? -ne 0 ]
-              then
-                echo "Push to branch $release_branch failed"
-                exit 1
-              fi
+              status=$?
+            fi
+            
+            if [ status -ne 0 ]
+            then
+              echo "Merge failed. Opening pull request."
+              gh pr create --head $source_branch --base $release_branch --reviewer paychex-mbuzzelli --reviewer paychex-msteves --title "Automatic merge failure" --body "There was a merge conflict automatically merging this branch"
+              exit 0
             fi
             
             source_branch=$release_branch
